receivers:
  zipkin:
  otlp:
    protocols:
      grpc:

exporters:
#  zipkin:
#    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
#    format: proto

  logging:
    loglevel: debug
#  prometheus:
#    endpoint: "127.0.0.1:9464"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [zipkin]
      processors: []
      exporters: [logging]
#    traces:
#      receivers: [otlp]
#      exporters: [zipkin]
#      processors: [batch]
#    metrics:
#      receivers: [otlp]
#      exporters: [prometheus]
#      processors: [batch]
