name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test for macOS
      run: swift test --enable-code-coverage
    - name: Upload Code coverage
      run: |
        curl -Os https://uploader.codecov.io/latest/macos/codecov
        chmod +x codecov
        codecovpath=$(swift test --show-codecov-path)
        ./codecov -f $codecovpath
